//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OGLTest.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OGLTest.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #version 140
        ///
        ///uniform sampler2D myTexture;
        ///in vec2 vTexCoord;
        ///
        ///void main(void)
        ///{
        ///   gl_FragColor = texture2D(myTexture, vTexCoord);
        ///}.
        /// </summary>
        internal static string FragmentShader1 {
            get {
                return ResourceManager.GetString("FragmentShader1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #version 140
        ///#define N     100
        ///#define EPS   0.001
        ///
        ///in vec3 in_Vertex;
        ///in vec3 in_Normal;
        ///in vec2 in_TexCoord;
        ///in ivec4 in_BoneIndexes1;
        ///in ivec4 in_BoneIndexes2;
        ///out vec2 vTexCoord;
        ///uniform mat4 in_Bones[N];
        ///uniform int in_IsAnimated;
        ///uniform mat4 in_MVP;
        ///uniform vec3 in_ObjectPos;
        ///
        ///vec4 transform(vec4 src, mat4 mat)
        ///{
        ///	vec4 transres;
        ///	transres.x = src.x * mat[0].x + 
        ///				src.y * mat[1].x + 
        ///				src.z * mat[2].x + 
        ///				src.w * mat[3].x;
        ///	transres.y = src.x * mat[0].y + 
        ///				src.y * m [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string VertexShader1 {
            get {
                return ResourceManager.GetString("VertexShader1", resourceCulture);
            }
        }
    }
}
